openapi: '3.0.2'
servers:
  - url: "http://localhost:8080/poc-st"
    description: "Dev server"
info:
  title: Organizations & Users Management
  version: '1.0'
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: Use `admin` / `admin` as the test credentials
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Provide an accessToken generated by Keycloak
        
  schemas:
    ApiErrorDetail:
      type: object
      description: "API Error detail"
      properties:
        code:
          type: string
          x-extensible-enum:
            - "LIST_NOT_NULL_NOT_EMPTY"
            - "NOT_NULL"
            - "NOT_EMPTY"
            - "PAYLOAD"
            - "LENGTH"
          description: |
            Detail error code, for example validation errors.
          example: "NOT_NULL"
        field:
          type: string
          description: "Field concerned by error, for example when a field length constraint is violated"
          example: "firstName"
        message:
          type: string
          description: "A human readable error message"
          example: "Invalid field [firstName] size, expected [1-50]"
    ApiError:
      type: object
      description: "Standard API error"
      required:
        - "status"
        - "kind"
        - "code"
      properties:
        status:
          type: number
          format: integer
          description: "HTTP status code (400, 409, 500, ...)"
          nullable: false
        kind:
          type: string
          description: "Error kind"
          default: "FUNCTIONAL"
          nullable: false
          enum:
            - FUNCTIONAL          
            - TECHNICAL
        code:
          type: string
          description: "Error code (UNIQUE)"
          nullable: false
          x-extensible-enum:
            - "ORG_CODE_ALREADY_USED"
            - "USER_EMAIL_ALREADY_USED"      
        message:
          type: string
          description: "A human readeable error message"
          example: "Email [test@test.fr] already in use"
          nullable: false
        debugMessage:
          type: string
          description: "Debug message (stacktrace), only for TECHNICAL errors"
          nullable: true
        errorUid:
          type: string
          description: "Unique identifier of technical error dump"
          nullable: true
          example: "baa901c1-1e3e-4388-84a1-1940dc3fc575"
        details:
          type: array
          description: "Error details"
          items:
            $ref: "#/components/schemas/ApiErrorDetail"
    ApiVersion:
      type: object
      description: "Api version"
      properties:
        version:
          type: string
          default: "v1"
          nullable: false
        category:
          type: string
          description: "Api category (system, users, orgs, ...)"
          nullable: false
          default: "organizations"
        code:
          type: string
          description: "API code (e.g: list, create, update, delete, ...)"
          nullable: false
        uri:
          type: string
          description: "API uri"
          default: "/api/v1/tenants/{tenantUid}/organizations/{orgUid}"
          nullable: false
    ApiVersionList:
      type: object
      properties:
        apiVersions:
          type: array
          items:
            $ref: "#/components/schemas/ApiVersion"        
    Uid:
      type: object
      properties:
        uid:
          type: string
          description: "Unique identifier (UUID)"
          externalDocs:
            url: "https://schema.org/identifier"
          nullable: false
          example: "e2e1e622-d05a-42f1-a4d9-5addef76f3be"
    Tenant:
      type: object
      required:
        - "code"
        - "label"
      properties:
        code:
          type: string
          description: "Short internal code (UNIQUE)"
          minimum: 0
          maximum: 50
          nullable: false
          example: "my_tenant_1"
        label:
          type: string
          description: "Label"
          minimum: 0
          maximum: 80
          nullable: false
          example: "My Tenant 1"
    TenantDisplay:
      type: object
      description: "Tenant DTO for display"
      properties:
        uid:
          type: string
          description: "Unique identifier"
          externalDocs:
            url: "https://schema.org/identifier"
          nullable: false
          example: "e2e1e622-d05a-42f1-a4d9-5addef76f3be"
        code:
          type: string
          description: "Short internal code (UNIQUE)"
          minimum: 0
          maximum: 50
          nullable: false
          example: "my_tenant_1"
        label:
          type: string
          description: "Label"
          minimum: 0
          maximum: 80
          nullable: false
          example: "My Tenant 1"
    TenantsList:
      type: object
      description: "Tenants list"
      properties:
        tenants:
          type: object
          properties:
            tenants:
              type: array
              items:
                $ref: "#/components/schemas/TenantDisplay"
    OrganizationCommons:
      type: object
      description: "Organization basic infos"
      properties:
        code:
          type: string
          description: "Short internal code (UNIQUE)"
          minimum: 0
          maximum: 50
          nullable: false
          example: "my_tenant_1"
        label:
          type: string
          description: "Label"
          minimum: 0
          maximum: 80
          nullable: false
          example: "My Tenant 1"
        kind:
          type: number
          format: integer
          description: |
            Organization kind:
              0: Tenant
              1: Bu
              2: Community
              3: Enterprise
          enum:
            - 0
            - 1
            - 2
            - 3
        status:
          type: number
          format: integer
          description: |
            Organization Status:
              0: Draft
              1: Active
              2: Inactive
          enum:
            - 0
            - 1
            - 2
        country:
          type: string
          description: "Country code (ISO Alpha 2)"
          example: "fr"
    Organization:
      type: object
      description: "Organization"
      properties:
        commons:
          type: object
          $ref: "#/components/schemas/OrganizationCommons"
    OrganizationLight:
      type: object
      description: "Liight organization representation"
      properties:
        uid:
          type: string
          description: "Unique identifier"          
        label:
          type: string
          description: "Label"
          minimum: 0
          maximum: 80
          nullable: false
          example: "My Tenant 1"
        kind:
          type: number
          format: integer
          description: |
            Organization kind:
              0: Tenant
              1: Bu
              2: Community
              3: Enterprise
          enum:
            - 0
            - 1
            - 2
            - 3
        status:
          type: number
          format: integer
          description: |
            Organization Status:
              0: Draft
              1: Active
              2: Inactive
          enum:
            - 0
            - 1
            - 2
    OrganizationList:
      type: object
      description: "Organizations list for display"
      properties:
        nbResults:
          type: integer
          description: "Total nb of results"
        nbPages:
          type: integer
          description: "Number of pages"
        organizations:
          type: array
          description: "Organizations list"
          items:
            $ref: "#/components/schemas/OrganizationLight"
    UserCredentials:
      description: "User"
      required:
        - "login"
        - "email"
      properties:
        login:
          type: string
          description: "Login"
          nullable: false
        email:
          type: string
          description: "Email"
          nullable: false
    UserCommons:
      description: "Common user infos"
      required:
        - "firstName"
        - "lastName"
      properties:
        firstName:
          type: string
          nullable: false
          description: "First name"
        lastName:
          type: string
          nullable: false
          description: "Last name"
        middleName:
          type: string
          nullable: false
          description: "Middle name"
    User:
      description: "User data"
      required:
        - "commons"
        - "credentials"
        - "status"
      properties:
        commons:
          type: object
          nullable: false
          $ref: "#/components/schemas/UserCommons"
        credentials:
          type: object
          nullable: false
          $ref: "#/components/schemas/UserCredentials"
        status:
          type: number
          format: integer
          description: |
            0: draft
            1: active
            2: suspended          
    UserDisplay:
      type: object
      description: "User display"
      required:
        - "uid"
        - "login"
        - "email"
        - "firstName"
        - "lastName"
        - "organization"
      properties:
        uid:
          type: string
          description: "Unique identifier"
          nullable: false
        login:
          type: string
          description: "Login"
          nullable: false
        email:
          type: string
          description: "Email"
          nullable: false
        firstName:
          type: string
          description: "First name"
          nullable: false
        lastName:
          type: string
          description: "Last name"
          nullable: false
        middleName:
          type: string
          description: "Last name"
          nullable: false
        organization:
          type: object
          $ref: "#/components/schemas/OrganizationLight"
    UsersList:
      type: object
      description: "Users list"
      properties:
        users:
          type: array
          items:
            $ref: "#/components/schemas/UserDisplay"
    Sector:
      type: object
      description: "Sector"
      required:
        - "code"
        - "label"
      properties:
        code:
          type: string
          nullable: false
          description: "Sector code (UNIQUE)"
          minimum: 1
          maximum: 50
        label:
          type: string
          nullable: false
          description: "Sector label"
          minimum: 1
          maximum: 80
        parentUid:
          type: string
          nullable: true
          description: "Parent sector uid"
          minimum: 40
          maximum: 40
    SectorDisplay:
      description: "Sector display"
      properties:
        uid:
          type: string
          description: "Sector unique identifier"
          nullable: false
        code:
          type: string
          description: "Sector code (UNIQUE)"
          nullable: false
        label:
          type: string
          description: "Sector label"
          nullable: false
        root:
          type: boolean
          description: "Is sector root organization sector"
          nullable: false
        parentUid:
          type: string
          description: "Parent sector uid"
          nullable: true
        children:
          type: array
          nullable: true
          items:
            $ref: "#/components/schemas/SectorDisplay"
    SystemErrorTemporal:
      description: "System error temporal data"
      properties:
        timestamp:
          type: string
          description: "System error file timestamp"
          example: "2024-11-04-09-39-10-282"
        pattern:
          type: string
          description: "System error file timestamp pattern"
          example: "yyyy-MM-dd-HH-mm-ss-SSS"
    SystemErrorFile:
      type: object
      description: "System error file"
      properties:
        temporal:
          type: object
          $ref: "#/components/schemas/SystemErrorTemporal"
        moduleName:
          type: string
          description: "Module name: (e.g: poc-st)"
          example: "poc-st"
          nullable: false
        uid:
          type: string
          description: "System error file uid"
          example: "c2b65d83-e747-4641-ab24-53088c419563"
          nullable: false
        fullFileName:
          type: string
          description: "System error full file name"
          example: "2024-11-04-09-39-10-282_poc-st_791dc7fb-823c-4a3a-aaef-4e2ef58d8e36.log"
          nullable: false
        content:
          type: string
          description: "System error files content"
          nullable: true
          example: "Lorem ipsum sit amet"
    SystemErrorList:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: "#/components/schemas/SystemErrorFile"
paths:
  /api/v1/tenants:
    get:
      tags:
        - "Tenants"
      description: "List tenants"
      summary: "List tenants"
      security:
        - bearerAuth: []
      responses:
        '200':
          description: "Tenants list"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TenantsList"
              example:
                tenants:
                - uid: "0bb555bf-87b2-4c0f-b802-c1c34aa058da"
                  code: "rennes"
                  label: "Rennes"
                - uid: "baa901c1-1e3e-4388-84a1-1940dc3fc575"
                  code: "caen"
                  label: "Caen"
        '500':
          description: "Technical error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
              example:
                kind: "TECHNICAL"
                code: "INTERNAL_SERVER_ERROR"
                status: "500"
                message: "ERROR: duplicate key value violates unique constraint ...."
                debugMessage: "org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL [insert into ..."
                errorUid: "0bb555bf-87b2-4c0f-b802-c1c34aa058da"
    post:
      tags:
        - "Tenants"
      description:  |
        Create a tenant.

        Provide code "crash" to throw an internal error
      summary: |
        Create a tenant

        Provide code "crash" to throw an internal error
      security: []
      requestBody:
        description: "Create tenant"
        content:
          appliation/json:
            schema:
              $ref: "#/components/schemas/Tenant"
      responses:
        '201':
          description: "Created successfully"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Uid"        
        '400':
          description: "Business error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
              example:
                kind: "FUNCTIONAL"
                code: "BAD_REQUEST"
                status: "400"
                message: "ArgumentNotValid"
                details:
                  - code: "NOT_NULL"
                    field: "code"
                    message: "Field [code] is required"
                  - code: "LENGTH"
                    field: "label"
                    message: "Invalid field [label] size, expected [1-80]"        
        '409':
          description: "Business error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
              example:
                kind: "FUNCTIONAL"
                code: "TENANT_CODE_ALREADY_USED"
                status: "409"
                message: "Tenant with code [rennes-01] already in use"
        '500':
          description: "Technical error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
              example:
                kind: "TECHNICAL"
                code: "INTERNAL_SERVER_ERROR"
                status: "500"
                message: "ERROR: duplicate key value violates unique constraint ...."
                debugMessage: "org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL [insert into ..."
                errorUid: "0bb555bf-87b2-4c0f-b802-c1c34aa058da"
  /api/v1/tenants/{uid}:
    get:
      tags:
        - "Tenants"
      description: "Find tenant by uid"
      summary: "Find tenant by uid"
      security: []
      parameters:
        - name: uid
          in: path
          description: "Tenant's unique identifier"
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "Tenants list"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TenantDisplay"
              example:
                uid: "0bb555bf-87b2-4c0f-b802-c1c34aa058da"
                code: "rennes"
                label: "Rennes"
        '404':
          description: "Tenant not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
              example:
                kind: "FUNCTIONAL"
                code: "TENANT_NOT_FOUND"
                status: "404"
                message: "Tenant with uid [0bb555bf-87b2-4c0f-b802-c1c34aa058da] not found"
        '500':
          description: "Tenants list"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
              example:
                kind: "TECHNICAL"
                code: "INTERNAL_SERVER_ERROR"
                status: "500"
                message: "ERROR: duplicate key value violates unique constraint ...."
                debugMessage: "org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL [insert into ..."
                errorUid: "0bb555bf-87b2-4c0f-b802-c1c34aa058da"
    post:
      tags:
        - "Tenants"
      description: "Update tenant by uid"
      summary: "Update tenant by uid"
      security: []
      parameters:
        - name: uid
          in: path
          description: "Tenant's unique identifier"
          required: true
          schema:
            type: string
      requestBody:
        description: "Update tenant payload"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Tenant"
      responses:
        '204':
          description: "Update success"
        '404':
          description: "Tenant not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
              example:
                kind: "FUNCTIONAL"
                code: "TENANT_NOT_FOUND"
                status: "404"
                message: "Tenant with uid [0bb555bf-87b2-4c0f-b802-c1c34aa058da] not found"
        '400':
          description: "Business error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
              example:
                kind: "FUNCTIONAL"
                code: "BAD_REQUEST"
                status: "400"
                message: "ArgumentNotValid"
                details:
                  - code: "NOT_NULL"
                    field: "code"
                    message: "Field [code] is required"
                  - code: "LENGTH"
                    field: "label"
                    message: "Invalid field [label] size, expected [1-80]"        
        '409':
          description: "Business error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
              example:
                kind: "FUNCTIONAL"
                code: "TENANT_CODE_ALREADY_USED"
                status: "409"
                message: "Tenant with code [rennes-01] already in use"
        '500':
          description: "Tenants list"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
              example:
                kind: "TECHNICAL"
                code: "INTERNAL_SERVER_ERROR"
                status: "500"
                message: "ERROR: duplicate key value violates unique constraint ...."
                debugMessage: "org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL [insert into ..."
                errorUid: "0bb555bf-87b2-4c0f-b802-c1c34aa058da"
    delete:
      tags:
        - "Tenants"
      description: "Delete tenant by uid"
      summary: "Delete tenant by uid"
      security: []
      parameters:
        - name: uid
          in: path
          description: "Tenant's unique identifier"
          required: true
          schema:
            type: string
      responses:
        '204':
          description: |
            Delete succes (deleting a tenant deletes all linked resources like organizations, sectors & users)
        '404':
          description: "Tenant not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
              example:
                kind: "FUNCTIONAL"
                code: "TENANT_NOT_FOUND"
                status: "404"
                message: "Tenant with uid [0bb555bf-87b2-4c0f-b802-c1c34aa058da] not found"
        '500':
          description: "Tenants list"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
              example:
                kind: "TECHNICAL"
                code: "INTERNAL_SERVER_ERROR"
                status: "500"
                message: "ERROR: duplicate key value violates unique constraint ...."
                debugMessage: "org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL [insert into ..."
                errorUid: "0bb555bf-87b2-4c0f-b802-c1c34aa058da"
  /api/v1/tenants/{uid}/organizations:
    get:
      tags:
        - "Organizations"
      description: "List organizations"
      summary: "List organizations"
      security: []
      parameters:
        - name: uid
          in: path
          description: "Tenant's unique identifier"
          required: true
          schema:
            type: string
        - name: filter
          in: query
          description: |
            Search filter: (column) (comparison) ('value') (operator) (column) (comparison) ('value')
            
            Comparison:
              - eq: Equals
              - ne: NotEquals
              - gt: Greater than
              - ge: Greater or equals
              - lt: Lower then
              - le: Lower or equals
              - lk: Like

            Operator:
              - and: Logical AND
              - or: Logical OR

            Example: (name eq 'Rennes' or name eq 'Cesson') and (code eq 'rn01' or code eq 'ces01)'
          required: false
          schema:
            type: string
        - name: index
          in: query
          description: "Page index"
          required: true
          schema:
            type: integer
        - name: size
          in: query
          description: "Nb of results per page"
          required: true
          schema:
            type: integer
        - name: orderBy
          in: query
          description: |
            Order by column, (+-)columnName pattern

            Example: +name
          required: true
          schema:
            type: integer    
      responses:
        '200':
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrganizationList"
              example:
                nbResults: 100
                nbPages: 10
                organizations:
                  - uid: "0bb555bf-87b2-4c0f-b802-c1c34aa058da"
                    code: "rennes-01"
                    label: "Rennes"
                    kind: "BU"
                    status: "ACTIVE"
        '404':
          description: "Tenant not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
              example:
                kind: "FUNCTIONAL"
                code: "TENANT_NOT_FOUND"
                status: "404"
                message: "Tenant with uid [0bb555bf-87b2-4c0f-b802-c1c34aa058da] not found"
        '500':
          description: "Technical error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
              example:
                kind: "TECHNICAL"
                code: "INTERNAL_SERVER_ERROR"
                status: "500"
                message: "ERROR: duplicate key value violates unique constraint ...."
                debugMessage: "org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL [insert into ..."
                errorUid: "0bb555bf-87b2-4c0f-b802-c1c34aa058da"
    post:
      tags:
        - "Organizations"
      description: "Create an organization"
      summary: "Create an organization"
      security: []
      parameters:
        - name: uid
          in: path
          description: "Tenant's unique identifier"
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Organization"
            example:
              - commons:
                - code: "rennes-01" 
                  label: "Rennes 01"
                  kind: 0
                  status: 1
                  country: "fr"
      responses:
        '201':
          description: "Created successfully"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Uid"
        '404':
          description: "Tenant not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
              example:
                kind: "FUNCTIONAL"
                code: "TENANT_NOT_FOUND"
                status: "404"
                message: "Tenant with uid [0bb555bf-87b2-4c0f-b802-c1c34aa058da] not found"
        '400':
          description: "Business error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
              example:
                kind: "FUNCTIONAL"
                code: "BAD_REQUEST"
                status: "400"
                message: "ArgumentNotValid"
                details:
                  - code: "NOT_NULL"
                    field: "code"
                    message: "Field [code] is required"
                  - code: "LENGTH"
                    field: "label"
                    message: "Invalid field [label] size, expected [1-80]"        
        '409':
          description: "Business error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
              example:
                kind: "FUNCTIONAL"
                code: "ORG_CODE_ALREADY_USED"
                status: "409"
                message: "Organization with code [rennes-01] already in use"
        '500':
          description: "Tenants list"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
              example:
                kind: "TECHNICAL"
                code: "INTERNAL_SERVER_ERROR"
                status: "500"
                message: "ERROR: duplicate key value violates unique constraint ...."
                debugMessage: "org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL [insert into ..."
                errorUid: "0bb555bf-87b2-4c0f-b802-c1c34aa058da"
  /api/v1/tenants/{uid}/organizations/{orgUid}:
    get:
      tags:
        - "Organizations"
      description: "Get organizations details"
      summary: "Get organization details"
      security: []
      parameters:
        - name: uid
          in: path
          description: "Tenant's unique identifier"
          required: true
          schema:
            type: string
        - name: orgUid
          in: path
          description: "Organization's unique identifier"
          required: true
          schema:
            type: string
        - name: fetchSectors
          in: query
          description: "Fetch sectors hierarchy"
          required: false
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Organization"
    post:
      tags:
        - "Organizations"
      description: "Create organization"
      summary: "Create organization"
      security: []
      parameters:
        - name: uid
          in: path
          description: "Tenant's unique identifier"
          required: true
          schema:
            type: string
        - name: orgUid
          in: path
          description: "Organization's unique identifier"
          required: true
          schema:
            type: string
      requestBody:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Organization"
              example:
                - commons:
                  - code: "rennes-01" 
                    label: "Rennes 01"
                    kind: 0
                    status: 1
                    country: "fr"
      responses:
        '204':
          description: "Update successfull"
        '404':
          description: "Organization not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
              example:
                kind: "FUNCTIONAL"
                code: "ORG_NOT_FOUND"
                status: "404"
                message: "Organization with uid [0bb555bf-87b2-4c0f-b802-c1c34aa058da] not found"
        '400':
          description: "Business error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
              example:
                kind: "FUNCTIONAL"
                code: "BAD_REQUEST"
                status: "400"
                message: "ArgumentNotValid"
                details:
                  - code: "NOT_NULL"
                    field: "code"
                    message: "Field [code] is required"
                  - code: "LENGTH"
                    field: "label"
                    message: "Invalid field [label] size, expected [1-80]"        
        '409':
          description: "Business error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
              example:
                kind: "FUNCTIONAL"
                code: "ORG_CODE_ALREADY_USED"
                status: "409"
                message: "Organization with code [rennes-01] already in use"
        '500':
          description: "Tenants list"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
              example:
                kind: "TECHNICAL"
                code: "INTERNAL_SERVER_ERROR"
                status: "500"
                message: "ERROR: duplicate key value violates unique constraint ...."
                debugMessage: "org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL [insert into ..."
                errorUid: "0bb555bf-87b2-4c0f-b802-c1c34aa058da"
    delete:
      tags:
        - "Organizations"
      description: "Delete organization"
      summary: "Delete organization"
      security: []
      parameters:
        - name: uid
          in: path
          description: "Tenant's unique identifier"
          required: true
          schema:
            type: string
        - name: orgUid
          in: path
          description: "Organization's unique identifier"
          required: true
          schema:
            type: string
      responses:
        '204':
          description: "Delete successfull"
        '404':
          description: "Organization not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
              example:
                kind: "FUNCTIONAL"
                code: "ORG_NOT_FOUND"
                status: "404"
                message: "Organization with uid [0bb555bf-87b2-4c0f-b802-c1c34aa058da] not found"
  /api/v1/tenants/{uid}/organizations/{orgUid}/users:
    post:
      description: "Create user"
      summary: "Create user"
      security: []
      tags:
        - "Users"
      parameters:
        - name: uid
          in: path
          description: "Tenant's unique identifier"
          required: true
          schema:
            type: string
        - name: orgUid
          in: path
          description: "Organization's unique identifier"
          required: true
          schema:
            type: string
      requestBody:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
              example:
                commons:
                  firstName: "Margaret"
                  lastName: "HAMILTON"
                  middleName: "M"
                credentials:
                  login: "mhamilton"
                  email: "m.hamilton@nasa.gov"
                status: 1
      responses:
        '201':
          description: "Creation success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Uid"
        '404':
          description: "Organization not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
              example:
                kind: "FUNCTIONAL"
                code: "ORG_NOT_FOUND"
                status: "404"
                message: "Organization with uid [0bb555bf-87b2-4c0f-b802-c1c34aa058da] not found"
        '400':
          description: "Business error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
              example:
                kind: "FUNCTIONAL"
                code: "BAD_REQUEST"
                status: "400"
                message: "ArgumentNotValid"
                details:
                  - code: "NOT_NULL"
                    field: "code"
                    message: "Field [firstName] is required"
                  - code: "LENGTH"
                    field: "label"
                    message: "Invalid field [lastName] size, expected [1-50]"
        '409':
          description: "Business error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
              example:
                kind: "FUNCTIONAL"
                code: "USER_LOGIN_ALREADY_USED"
                status: "409"
                message: "Login [mhamilton] already in use"
        '500':
          description: "Tenants list"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
              example:
                kind: "TECHNICAL"
                code: "INTERNAL_SERVER_ERROR"
                status: "500"
                message: "ERROR: duplicate key value violates unique constraint ...."
                debugMessage: "org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL [insert into ..."
                errorUid: "0bb555bf-87b2-4c0f-b802-c1c34aa058da"
    get:
      tags:
        - "Users"
      description: "List users"
      summary: "List users"
      security: []
      parameters:
        - name: uid
          in: path
          description: "Tenant's unique identifier"
          required: true
          schema:
            type: string
        - name: orgUid
          in: path
          description: "Organization's unique identifier"
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "Users list"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UsersList"
        '404':
          description: "Organization not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
              example:
                kind: "FUNCTIONAL"
                code: "ORG_NOT_FOUND"
                status: "404"
                message: "Organization with uid [0bb555bf-87b2-4c0f-b802-c1c34aa058da] not found"
  /api/v1/tenants/{uid}/organizations/{orgUid}/users/{userUid}:
    post:
      tags:
        - "Users"
      description: "Update user"
      summary: "Update user"
      security: []
      parameters:
        - name: uid
          in: path
          description: "Tenant's unique identifier"
          required: true
          schema:
            type: string
        - name: orgUid
          in: path
          description: "Organization's unique identifier"
          required: true
          schema:
            type: string
        - name: userUid
          in: path
          description: "Users's unique identifier"
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
            example:
              commons:
                firstName: "Margaret"
                lastName: "HAMILTON"
                middleName: "M"
              credentials:
                login: "mhamilton"
                email: "m.hamilton@nasa.gov"
              status: 1
              
      responses:
        '204':
          description: "Update success"
    delete:
      description: "Delete user"
      summary: "Delete user"
      security: []
      tags:
        - "Users"
      parameters:
        - name: uid
          in: path
          description: "Tenant's unique identifier"
          required: true
          schema:
            type: string
        - name: orgUid
          in: path
          description: "Organization's unique identifier"
          required: true
          schema:
            type: string
        - name: userUid
          in: path
          description: "Users's unique identifier"
          required: true
          schema:
            type: string
      responses:
        '204':
          description: "Deletion success"
        '404':
          description: "User not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
              example:
                kind: "FUNCTIONAL"
                code: "USER_NOT_FOUND"
                status: "404"
                message: "User with uid [0bb555bf-87b2-4c0f-b802-c1c34aa058da] not found"
  /api/v1/system/versions:
    get:
      description: "Get API versions list"
      summary: "Get API versions list"
      security:
        - basicAuth: []
      tags:
        - System
      responses:
        '200':
          description: "Success"
          content:
            application/json:
              schema:                
                $ref: "#/components/schemas/ApiVersionList"
  /api/v1/system/techGaugeReset:
    delete:
      description: "Reset technical errors gauge"
      summary: "Reset technical errors gauge"
      security:
        - basicAuth: []
      tags:
        - System
      responses:
        '204':
          description: "Success"
  /api/v1/system/wakeup:
    post:
      description: "Send wake-up message to event listener in order to trigger kafka push"
      summary: "Send wake-up message to event listener in order to trigger kafka push"
      security:
        - basicAuth: []
      tags:
        - System
      responses:
        '204':
          description: "Success"
  /api/v1/system/errors:
    get:
      description: "List system errors files"
      summary: "List system errors files"
      security:
        - basicAuth: []
      tags:
       - System
      responses:
        '200':
          description: "List system error files"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SystemErrorList"
  /api/v1/system/errors/{fileName}:
    get:
      description: "Get system error file content"
      summary: "Get system error file content"
      security:
        - basicAuth: []
      tags:
        - System      
      parameters:
        - name: fileName
          in: path
          description: "Full file name"
          required: true
          schema:
            type: string        
      responses:
        '200':
          description: "System file content"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SystemErrorFile"
  /api/v1/tenants/{uid}/organizations/{orgUid}/sectors:
    post:
      description: "Create sector"
      summary: "Create user"
      security: []
      tags:
        - "Sectors"        
      parameters:
        - name: uid
          in: path
          description: "Tenant's unique identifier"
          required: true
          schema:
            type: string
        - name: orgUid
          in: path
          description: "Organization's unique identifier"
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Sector"
            example:
              - code: "rennes-wst"
                label: "Rennes west"
                parentUid: "0bb555bf-87b2-4c0f-b802-c1c34aa058da"
      responses:
        '201':
          description: "Create success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Uid"
        '404':
          description: "Organization not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
              example:
                kind: "FUNCTIONAL"
                code: "ORG_NOT_FOUND"
                status: "404"
                message: "Organization with uid [0bb555bf-87b2-4c0f-b802-c1c34aa058da] not found"
        '400':
          description: "Bad request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
              example:
                kind: "FUNCTIONAL"
                code: "BAD_REQUEST"
                status: "400"
                message: "ArgumentNotValid"
                details:
                  - code: "NOT_NULL"
                    field: "code"
                    message: "Field [code] is required"
                  - code: "LENGTH"
                    field: "label"
                    message: "Invalid field [label] size, expected [1-80]"
        '409':
          description: "Business error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
              example:
                kind: "FUNCTIONAL"
                code: "SECTOR_NOT_FOUND"
                status: "409"
                message: "Sector code [rennes-wst] already in use"
        '500':
          description: "Internal Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
              example:
                kind: "TECHNICAL"
                code: "INTERNAL_SERVER_ERROR"
                status: "500"
                message: "ERROR: duplicate key value violates unique constraint ...."
                debugMessage: "org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL [insert into ..."
                errorUid: "0bb555bf-87b2-4c0f-b802-c1c34aa058da"
    get:
      tags:
        - "Sectors"
      description: "Sectors list with hierarchy"
      summary: "Sectors list with hierarchy"
      security: []
      parameters:
        - name: uid
          in: path
          description: "Tenant's unique identifier"
          required: true
          schema:
            type: string
        - name: orgUid
          in: path
          description: "Organization's unique identifier"
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "Sectors list"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SectorDisplay"
              example:
                uid: "0bb555bf-87b2-4c0f-b802-c1c34aa058da"
                code: "rennes"
                label: "Rennes"
                root: true
                children:
                  - uid: "baa901c1-1e3e-4388-84a1-1940dc3fc575"
                    code: "rennes-west"
                    label: "Rennes West"
                    root: false
                    parentUid: "0bb555bf-87b2-4c0f-b802-c1c34aa058da"
                  - uid: "e2e1e622-d05a-42f1-a4d9-5addef76f3be"
                    code: "rennes-east"
                    label: "Rennes East"
                    root: false
                    parentUid: "0bb555bf-87b2-4c0f-b802-c1c34aa058da"
        '404':
          description: "Organization not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
              example:
                kind: "FUNCTIONAL"
                code: "ORG_NOT_FOUND"
                status: "404"
                message: "Organization with uid [0bb555bf-87b2-4c0f-b802-c1c34aa058da] not found"
        '500':
          description: "Technical error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
              example:
                kind: "TECHNICAL"
                code: "INTERNAL_SERVER_ERROR"
                status: "500"
                message: "ERROR: duplicate key value violates unique constraint ...."
                debugMessage: "org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL [insert into ..."
                errorUid: "0bb555bf-87b2-4c0f-b802-c1c34aa058da"
  /api/v1/tenants/{uid}/organizations/{orgUid}/sectors/{sectorUid}:
    post:
      description: "Update sector"
      summary: "Update sector"
      security: []
      tags:
        - "Sectors"
      parameters:
        - name: uid
          in: path
          description: "Tenant's unique identifier"
          required: true
          schema:
            type: string
        - name: orgUid
          in: path
          description: "Organization's unique identifier"
          required: true
          schema:
            type: string
        - name: sectorUid
          in: path
          description: "Sector's unique identifier"
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Sector"
            example:
              - code: "rennes-wst"
                label: "Rennes west"
                parentUid: "0bb555bf-87b2-4c0f-b802-c1c34aa058da"
      responses:
        '204':
          description: "Update success"
        '400':
          description: "Bad request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
              example:
                kind: "FUNCTIONAL"
                code: "BAD_REQUEST"
                status: "400"
                message: "ArgumentNotValid"
                details:
                  - code: "NOT_NULL"
                    field: "code"
                    message: "Field [code] is required"
                  - code: "LENGTH"
                    field: "label"
                    message: "Invalid field [label] size, expected [1-80]"  
        '404':
          description: "Sector not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
              example:
                kind: "FUNCTIONAL"
                code: "SECTOR_NOT_FOUND"
                status: "404"
                message: "Sector with uid [0bb555bf-87b2-4c0f-b802-c1c34aa058da] not found"
        '500':
          description: "Internal Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
              example:
                kind: "TECHNICAL"
                code: "INTERNAL_SERVER_ERROR"
                status: "500"
                message: "ERROR: duplicate key value violates unique constraint ...."
                debugMessage: "org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL [insert into ..."
                errorUid: "0bb555bf-87b2-4c0f-b802-c1c34aa058da"
    delete:
      description: "Delete sector"
      summary: "Delete sector"
      security: []
      tags:
        - "Sectors"
      parameters:
        - name: uid
          in: path
          description: "Tenant's unique identifier"
          required: true
          schema:
            type: string
        - name: orgUid
          in: path
          description: "Organization's unique identifier"
          required: true
          schema:
            type: string
        - name: sectorUid
          in: path
          description: "Sector's unique identifier"
          required: true
          schema:
            type: string
      responses:
        '204':
          description: "Delete success"
        '404':
          description: "Sector not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
              example:
                kind: "FUNCTIONAL"
                code: "SECTOR_NOT_FOUND"
                status: "404"
                message: "Sector with uid [0bb555bf-87b2-4c0f-b802-c1c34aa058da] not found"
        '409':
          description: "Functional error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
              example:
                kind: "FUNCTIONAL"
                code: "SECTOR_ROOT_DELETE_NOT_ALLOWED"
                status: "409"
                message: "Root sector cannot be deleted"
        '500':
          description: "Internal Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
              example:
                kind: "TECHNICAL"
                code: "INTERNAL_SERVER_ERROR"
                status: "500"
                message: "ERROR: duplicate key value violates unique constraint ...."
                debugMessage: "org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL [insert into ..."
                errorUid: "0bb555bf-87b2-4c0f-b802-c1c34aa058da"
